### ISSUE TITLE
Failed build wheel when pip installing pyymw16

### ISSUE THREAD

**Issue by abatten** [FRBs/pygedm#1]
When I install pyymw16 from pip I am given the following error. Although it does install correctly, it gives the illusion the process has failed.

```
ModuleNotFoundError: No module named 'pybind11'

  ----------------------------------------
  Failed building wheel for pyymw16
  Running setup.py clean for pyymw16
Failed to build pyymw16
Installing collected packages: pybind11, pyymw16
  Running setup.py install for pyymw16 ... done
Successfully installed pybind11-2.2.4 pyymw16-2.0.4
```

I believe this is due to ``import pybind11`` in the setup.py file. It searches for a module within pyymw16 called pybind11 and when it can't find one it raises this error it then installs pybind11.

**Comment by telegraphic** [comment]
I added pybind to the `setup_requires`, which hopefully fixes this

**Comment by abatten** [comment]
Hopefully! I'll try installing it when 2.0.5 becomes available on pip.

**Comment by abatten** [comment]
The 2.0.5 version on Pypi is only available in for python 2.7 with OSX. Are you able to create the wheel for a Universal Python and OS?

i.e Add this to the top of your setup.cfg file.
```
[bdist_wheel]
universal=1
```
Then execute after clearing your dist directory.

```
python setup.py sdist bdist_wheel
twine upload dist/*
```

**Comment by telegraphic** [comment]
Just tried reuploading, looks like I needed to run the setup.py in py2 and py3?

**Comment by telegraphic** [comment]
Closing as a lot has changed and likely not an issue anymore (e.g. not called pyymw16 anymore!)
