### ISSUE TITLE
Old Version Available?

### ISSUE THREAD

**Issue by DemonLord13** [FRBs/pygedm#13]
I been having a import error after download 
This error have been talk in this github and one of the solutions was using a older version. 

There is any instructions for this?? or another solutions for the import errors.
Currently I am using spyder3(Anaconda) on an Ubuntu virtual machine.

![image](https://user-images.githubusercontent.com/86861855/124340078-b2faa680-db80-11eb-9700-4c707ded1d35.png)
![image](https://user-images.githubusercontent.com/86861855/124340105-d887b000-db80-11eb-9793-2697310f9bb7.png)

**Comment by telegraphic** [comment]
Hi @DemonLord13, I've updated the pypi version to 3.2.0, which fixes this issue.

This new version uses `f2c`, which you can get with `apt-get f2c` to install it globally in your VM, or you can use `conda install -c conda-forge f2c` to use the conda version and keep it in your conda environment.
