### ISSUE TITLE
Always getting dist=25000.0 regardless of given arguments

### ISSUE THREAD

**Issue by 0xCoto** [FRBs/pygedm#15]
I am looking to reproduce the distance computation from the example found in the README:
```python
# calculate distance for a given sky position and DM
dist, tau_sc = pygedm.dm_to_dist(123.4, 4.0, 200)
```
I've got a list of positions (`l`, `b`) and DMs `dm` for which I wish to derive the distance for every corresponding combination:
```python
distances = []

idx = 0
for dm_value in dm:
	distance, tau_sc = pygedm.dm_to_dist(l[idx], b[idx], dm_value)
	distances.append(str(distance))
	idx += 1

print(l[0], b[0], dm[0], distances[0])
print(l[1], b[1], dm[1], distances[1])
print(l[2], b[2], dm[2], distances[2])
```
However, it seems that I always get `25000.0 pc`, even though `l[i]`, `b[i]` and `dm[i]` vary:
```
356.64 -20.02 790.3 25000.0 pc
260.07 -38.35 350.0 25000.0 pc
274.72 -33.3 1187.0 25000.0 pc
```

What could be the cause of this issue?

Full script [here](https://github.com/HeRTA/FRBSTATS/blob/main/distances.py) in case I'm missing anything obvious.

---

Also, I believe there is a typo here (other than `(float)`), which may introduce a lot of confusion and give incorrect results (though definitely not the cause of the aforementioned issue):
```
     Args:
        l (float): galactic latitude in degrees
        b (float): galactic longitude in degrees
        dm (floa): Dispersion measure
```
***l*** should be considered galactic **longitude** and ***b*** should be considered galactic **latitude**. I'm not sure if the code also needs adjustments or if it's solely a docstring typo, but it's definitely something to be looked at and corrected.

Thanks a lot in advance!

**Comment by telegraphic** [comment]
Hi @0xCoto -- the NE2001 and YMW16 models are Galactic only, and do not include the halo, so what you're seeing there is that the code has reached the edge of the model and is not integrating further. 

If you use the inverse and plug in 25 kpc, you see that the DM contribution along those lines of sight is:

```
In [6]: pygedm.dist_to_dm(356.64, -20.02, 25000*u.pc)
Out[6]: (<Quantity 75.90722656 pc / cm3>, <Quantity 6.83889903e-06 s>)

In [7]: pygedm.dist_to_dm(60.07, -38.35, 25000.0)
Out[7]: (<Quantity 32.47999573 pc / cm3>, <Quantity 2.64335114e-07 s>)

In [8]: pygedm.dist_to_dm(274.72, -33.3, 25000.0)
Out[8]: (<Quantity 54.87789917 pc / cm3>, <Quantity 1.88222407e-06 s>)
```

So I believe the code is behaving, but perhaps it would make sense to raise a warning that you're integrating to the edge of the model?

--- 

This is definitely a typo! Thanks for picking this up -- the order (l,b) is correct so should just be the docstring.

**Comment by 0xCoto** [comment]
Hi Danny, many thanks for the quick response!

I see, this actually makes sense... Although I was already 'subconsciously' aware our extragalactic models were limited, I suppose the fact that this tool is under FRBs/ on GitHub tricked me to forget this for a second! :)

Would it be fair then to say this tool is primarily (solely?) intended for pulsars given the constraints of today's electron density models, or are there any utilities for FRBs that I'm overlooking?

**Comment by telegraphic** [comment]
Shoutout to [fruitbat](https://fruitbat.readthedocs.io/en/latest/user_guide/using_fruitbat.html), which probably does what you want 🦇. It lets you choose a method, cosmology and then will convert a DM to redshift:
https://fruitbat.readthedocs.io/en/latest/user_guide/method_and_cosmology.html

(fruitbat uses pygedm under the hood for Galactic DM calculations)

 > Would it be fair then to say this tool is primarily (solely?) intended for pulsars given the constraints of today's electron density models, or are there any utilities for FRBs that I'm overlooking?

Well, NE2001/YMW16 is cited in pretty much every FRB detection paper, so I'd say _not_ fair! To estimate FRB distances we still need to know the DM contribution of the Milky way. But it is true that `pygedm` only deals with the Milky Way, so is only part of the puzzle, and that it's useful for pulsars too.

**Comment by 0xCoto** [comment]
Ok, redshift is actually quite useful indeed!

Nice to hear fruitbat makes use of pygedm in the background; indeed galactic DM contribution is super important. Thanks for the suggestion, will definitely look into that!
