### ISSUE TITLE
Error in pygedm_app docker build

### ISSUE THREAD

**Issue by drsimmo** [FRBs/pygedm#16]
Hi,

FYI, when trying to build the pygedm_app using app/Dockerfile I get an error because the line:
`COPY ./assets/* /app/assets`
needs a terminating slash

Thanks,
Simon

**Comment by telegraphic** [comment]
Thanks @drsimmo! I've updated this, and added some better error handling to the web app.

**Comment by telegraphic** [comment]
apparently I did this, so closing issue
