### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by zhangxn1026** [FRBs/pygedm#24]
hi,
I encountered an error using the (pygedm.dist_to_dm method)
eg: DM, tau_sc = pygedm.dist_to_dm(204.0, -6.5, 2000.0, method='ne2001')
     Segment fault: Spit nuclei

**Comment by telegraphic** [comment]
Hi @zhangxn1026, I'm not able to replicate this, so looks like an installation issue.

I would recommend downloading this repository and installing via

```
pip install .
```

Then running the unit tests:

```
python setup.py test
```

If those do not pass, there is an installation issue on your end.

An alternative to getting up and running would be to use the Dockerfile (https://thenewstack.io/docker-basics-how-to-use-dockerfiles/) and install into a Docker container.
